export const ROUTES = {
  HOME: '/',
  SIGNUP: '/signup',
  LOGIN: '/login',
  WELCOME: '/welcome',
  SURVEY: '/survey',
  SEARCH: '/search',
  PRODUCT: '/product',
  PRODUCT_BY_ID: (id: string) => `/product/${id}`,
  CART: '/cart',
  ORDER: '/order',
  REVIEW: '/review',
  REVIEW_BY_ID: (id: string) => `/review/${id}`,
  REVIEW_ADD: '/review/add',
  REVIEW_MODIFY: '/review/modify',
  MYPAGE: {
    MAIN: '/mypage',
    INFO: '/mypage/info',
    ORDER: '/mypage/order',
    REVIEW: '/mypage/review',
    WITHDRAWAL: '/mypage/withdrawal',
  },
  ADMIN: {
    MAIN: '/admin',
    USER: '/admin/user',
    USER_BY_ID: (id: string) => `/admin/user/${id}`,
    USER_FORM: '/admin/user/form',
    CATEGORY: '/admin/product/category',
    CATEGORY_BY_ID: (id: string) => `/admin/product/category/${id}`,
    CATEGORY_FORM: '/admin/product/category/form',
    PRODUCT: '/admin/product',
    PRODUCT_BY_ID: (id: string) => `/admin/product/${id}`,
    PRODUCT_FORM: '/admin/product/form',
    POPULAR: '/admin/product/popular',
    POPULAR_BY_ID: (id: string) => `/admin/product/popular/${id}`,
    POPULAR_FORM: '/admin/product/popular/form',
    ORDER: '/admin/order',
    ORDER_BY_ID: (id: string) => `/admin/order/${id}`,
    ORDER_FORM: '/admin/order/form',
    NOTICE: '/admin/community/notice',
    NOTICE_BY_ID: (id: string) => `/admin/community/notice/${id}`,
    NOTICE_FORM: '/admin/community/notice/form',
    REVIEW: '/admin/community/review',
    REVIEW_BY_ID: (id: string) => `/admin/community/review/${id}`,
    REVIEW_FORM: '/admin/community/review/form',
    BANNER: '/admin/banner',
    BANNER_BY_ID: (id: string) => `/admin/banner/${id}`,
    BANNER_FORM: '/admin/banner/form',
  },
};
