export const ROUTES = {
  HOME: '/',
  SIGNUP: '/signup',
  LOGIN: '/login',
  WELCOME: '/welcome',
  SURVEY: '/survey',
  SEARCH: '/search',
  PRODUCT: '/product',
  PRODUCT_BY_ID: (id: string) => `/product/${id}`,
  CART: '/cart',
  ORDER: '/order',
  REVIEW: '/review',
  REVIEW_BY_ID: (id: string) => `/review/${id}`,
  REVIEW_ADD: '/review/add',
  REVIEW_MODIFY: '/review/modify',
  MYPAGE: {
    MYPAGE_MAIN: '/mypage',
    MYPAGE_INFO: '/mypage/info',
    MYPAGE_ORDER: '/mypage/order',
    MYPAGE_REVIEW: '/mypage/review',
    MYPAGE_WITHDRAWAL: '/mypage/withdrawal',
  },
  ADMIN: {
    USER: '/admin/user',
    USER_BY_ID: (id: string) => `/admin/user/${id}`,
    USER_MODIFY: '/admin/user/modify',
    CATEGORY: '/admin/category',
    CATEGORY_BY_ID: (id: string) => `/admin/category/${id}`,
    CATEGORY_ADD: '/admin/category/add',
    CATEGORY_MODIFY: '/admin/category/modify',
    PRODUCT: '/admin/product',
    PRODUCT_BY_ID: (id: string) => `/admin/product/${id}`,
    PRODUCT_ADD: '/admin/product/add',
    PRODUCT_MODIFY: '/admin/product/modify',
    ORDER: '/admin/order',
    ORDER_BY_ID: (id: string) => `/admin/order/${id}`,
    ORDER_MODIFY: '/admin/order/modify',
    REVIEW: '/admin/review',
    REVIEW_BY_ID: (id: string) => `/admin/review/${id}`,
    REVIEW_MODIFY: '/admin/review/modify',
  },
};
